apiVersion: v1
kind: Service
metadata:
  name: damp-starter-deploy
  labels:
    app: damp-starter
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: damp-starter
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: damp-starter-deploy
  labels:
    app: damp-starter
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: damp-starter
        tier: frontend
    spec:
      containers:
      - name: damp-starter-app
        image: docker.io/datphan/damp
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 80