version: '3'

services:
  mysqldb:
    image: "mysql:latest"

    ports:
      - "6603:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ALLOW_EMPTY_PASSWORD: "yes"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"

    ports:
      - "8080:80"

    environment:
      PMA_HOST: ${MYSQL_HOST}

    links:
      - ${MYSQL_HOST}

  dev:
    build: .

    image: ${DOCKER_IMAGE_DEV_PROD:-damp-starter}

    ports:
      - "80:80"

    volumes:
      - ./src:/var/www/html

    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      MYSQL_HOST: ${MYSQL_HOST}

    depends_on:
      - ${MYSQL_HOST}

volumes:
  mysql_data:
    driver: local
    
