version: '3'

services:
  review:
    image: ${DOCKER_IMAGE_REVIEW}
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html

    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST_REVIEW}

    depends_on:
      - mysqldb

    
