version: '3'

services:
  mysqldb:
    image: "mysql:latest"

    ports:
      - "6603:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ALLOW_EMPTY_PASSWORD: "yes"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"

   

    environment:
      PMA_HOST: ${MYSQL_HOST}

    links:
      - ${MYSQL_HOST}

  composer:
    image: "composer:latest"

    command: update

    volumes:
      - ./src:/app/

  dev:
    build: .

    image: ${DOCKER_IMAGE_DEV_PROD:-damp-starter}


    volumes:
      - ./src:/var/www/html
      - ./run-dev.sh:/opt/app/run-dev.sh
      - ./config/apache2/ports.tpl.conf:/etc/apache2/ports.tpl.conf
      - ./config/apache2/sites-enabled/000-default.tpl.conf:/etc/apache2/sites-enabled/000-default.tpl.conf

    working_dir: /opt/app

    command: sh run-dev.sh

    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      MYSQL_HOST: ${MYSQL_HOST}

    depends_on:
      - ${MYSQL_HOST}
      - composer

volumes:
  mysql_data:
    driver: local
    
